### ISSUE TITLE
Initialize?

### ISSUE THREAD

**Issue by heroheman** [thisislawatts/kirby-picture#1]
Hey - this is what i was looking for. 
I installed it on my uberspace server, made sure ive got gdlib on the machine - reloaded the page and.... nothing. The images havent been generated. 
So - am i missing something - do i have to initialize it somewhere? What permissions should the "pictures" folder have?
Sorry, maybe this is not an issue - more kind of support 

Edit: Also - i am using it in a snippet right now. 

... and the img is not in a `picture` element.

**Comment by thisislawatts** [comment]
Hey @heroheman, can I help out at all with this or did you end up finding a workaround? I'm in the middle of rewriting to make it **much** simpler to use not to mention Kirby V2 friendly

**Comment by heroheman** [comment]
Hi, since its more than two years ago, i have no idea what this was about. :)
i think i tried another plugin or solution. 

Edit: You asked me that last year. Wow. Right now the rewrite should be complete. 
Github should send notifications on answers, not on "ticket status" changes

**Comment by thisislawatts** [comment]
@heroheman no problem :) I was just tidying up.
Found this great plugin from one of Kirby team, could be useful for reference:
https://github.com/fabianmichael/kirby-imagekit
